### ISSUE TITLE
move code outside of the loop if it's not depending on it

### ISSUE THREAD

**Issue by incredibleLeitman** [samus9001/Slot-Machine-Game-Exercise#1]
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/7900d502d611ca37040a0a65aef9951f5c5cf319/Program.cs#L36-L41

Instead of creating a new grid and calculate the rows and cols in every iteration
you can just place it outside of the loop and only generate it once.

**Comment by samus9001** [comment]
Change made
