### ISSUE TITLE
What does this part in your condition achieve "matchedRows != rows && matchedColumns != cols" ?

### ISSUE THREAD

**Issue by incredibleLeitman** [samus9001/Slot-Machine-Game-Exercise#15]
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/255c372e656e27be278935e0f4c5125b5d2529b2/Program.cs#L118
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/255c372e656e27be278935e0f4c5125b5d2529b2/Program.cs#L129

Can you explain why you added that?

**Comment by samus9001** [comment]
@incredibleLeitman I believe it was because at one point the matchedRows++ and matchedColumns++ were executing after every go, which resulted in the jackpot win condition being incorrectly executed after three goes, but now it no longer seems necessary so I will remove them.
