### ISSUE TITLE
move if outside of the other input condition

### ISSUE THREAD

**Issue by incredibleLeitman** [samus9001/Slot-Machine-Game-Exercise#2]
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/7900d502d611ca37040a0a65aef9951f5c5cf319/Program.cs#L64-L78

This condition is nested inside a condition that checks the same variable for another value which means it basically gets never executed.
You want to move it at the same level as the ```input == "1"``` check or even use a switch

**Comment by samus9001** [comment]
Change made
