### ISSUE TITLE
prefer returning of values instead of modifying input parameters

### ISSUE THREAD

**Issue by incredibleLeitman** [samus9001/Slot-Machine-Game-Exercise#22]
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/45182ca06c5a7365ab6b9b199935dd69a9caf6f1/LogicMethods.cs#L135

It is more readable to let functions return a value that is used for manipulating some variable instead of providing the variable that you want to modify and also return that variable.

So instead of calling 
```
balance = LogicMethods.GrantWins(rowCnt, slotMachine, grid3x3, rows, cols, LARGE_WIN, MEDIUM_WIN, SMALL_WIN, balance);
```
which receives the balance, internally modify and finally returns it
you should just calculate the winnings and return them to add them to your balance. Somewhat like
```
int winnings = LogicMethods.GrantWins(rowCnt, slotMachine, grid3x3, rows, cols);
balance += winnings;
```

You already did this very similar when deducting the bet:
```
decreaseBalanceForGameRound = MAX_LOSS;
balance -= decreaseBalanceForGameRound;
```

**Comment by samus9001** [comment]
updated return values and calls for methods and now balance += winnings works correctly
