### ISSUE TITLE
jackpotMatch variable is not updating

### ISSUE THREAD

**Issue by samus9001** [samus9001/Slot-Machine-Game-Exercise#23]
jackpotMatch variable is not updating to true after the CheckJackpotMatch method is called and stays false so a jackpot can not occur.

**Comment by incredibleLeitman** [comment]
The reason for this is that you never assign a value to this variable other than in the initialization
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/aab68ef2effb1b5a7bee871b048149de51e3ce86/Program.cs#LL26C17-L26C43

You can verify this by searching for "jackpotMatch = " in your project.

To do so, you need to either set this value depending on a condition,
or return it from a function and set the value like
```
jackpotMatch = someFunction(...);

public static bool someFunction(...)
{
  bool myVal;
  // do something and calculate the value of myVal
  
  return myVal;
}
```
