### ISSUE TITLE
Simplify code

### ISSUE THREAD

**Issue by incredibleLeitman** [samus9001/Slot-Machine-Game-Exercise#7]
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/d346e2f4e1c2d4e55b9e52388560aa61ed03482e/Program.cs#L95-L122
You first manually check each line separately and grant a win if one line matches.
Then you iterate all lines (again) and grant a medium win if all lines match.
And lastly you check if all line and cols match to grant an even bigger win.

This means, if the user really manages to hit all line are the same, you don't only grant the jackpot but additionally the medium win and at least 6 time the small win, 
it this intentional? 

Another approach to solve this and also reducing your duplicated code would be to just check the amount of matching lines with the help of a loop:
For each line you check if the values are equal and if so, increase a counter by one -> if after that the counter equals the number of all rows this means all the lines are won, otherwise only one or two.

You do this the same way for columns but diagonals are not accounted into the Jackpot ☝️ 
If you refactor your logic like I suggested this could also be taken into account easily

**Comment by incredibleLeitman** [comment]
one part of this issue is still unsolved:
When a user manages to hit multiple rows or columns your program grants the win for each single line
AND additionally the checkpot. For example, of the user hits all 3 lines he receives the MEDIUM_MIN for 500
AND additionally 3 times the SMALL_WIN for each line for an extra 150 credits. 

Is this how your program should work, did you plan that intentionally?

I think, the bigger wins should overrule the single-line wins (because you also do that for the large and medium wins) and this would make your slotmachine more consistent in behaviour

**Comment by incredibleLeitman** [comment]
Instead of randomly adding more complex conditions, let us discuss this issue here.

How do you have planned your program to work? 
What are the win conditions and what amount does the user win on each criteria?

**Comment by samus9001** [comment]
@incredibleLeitman 

match on row x = small win, if two rows have a match that will be two small wins
match on col x = small win, if two cols have a match that will be two small wins
match on diag x = small win, if both diags have a match that will be two small wins

match on all rows = medium win, overrules any small win on row x
match on all cols = medium win, overrules any small win on col x

match on all elements = big win, overrules all other wins

**Comment by incredibleLeitman** [comment]
So it looks like you wanted your program for larger wins to overrule smaller ones, which is currently not the case 👆 
The reason is, that in your functions for evaluating how much correct lines were hit, you additionally also grant a win every time.

One possible solution to prevent this would be to split the *evaluation* of how many lines where hit
and the actual *grant* of wins depending on the matching lines into separate functions and call them in order.

**Comment by samus9001** [comment]
@incredibleLeitman I've created a method for increasing the balance when a small match win is triggered but the balance now only increments when there is a row match and not when there is a column or diagonal match. I'm not sure what exactly the issue is as the code used for the matches are effectively the same, which the new method checks for.

**Comment by incredibleLeitman** [comment]
This method almost resolves this issue because you now check if the amount of matching lines does not equal the needed count for the Jackpot or the big win 👍 
However, you now only grant one SMALL_WIN for matching rows, columns or diagonals -> If the user manages to get two matching rows for example, you only grant one SMALL_WIN.

Another approach would be, to first check if the user hits the jackpot, else if it was the big win, else if any matching rows, cols or diagonals were hit. Basically your "CheckJackpotOrBigWin" method combined with the "SmallBalanceIncrease"


But anyway, I really encourage you to attempt the next live call because you have clearly some lacking knowledge regarding methods 👆

**Comment by samus9001** [comment]
@incredibleLeitman I've combined the two methods but still have the issue of the balance increasing once instead of twice if there are two small matches. Not sure of a simple way to resolve this without using several if statements with magic numbers in the conditions.

I also now have an issue where the UI message for any match displays twice, which I don't understand why.

**Comment by incredibleLeitman** [comment]
![image](https://user-images.githubusercontent.com/24638443/235296085-e970ed38-ad92-4aea-b379-74636e202dc6.png)
This recently added code basically is responsible for granting small wins for rows, cols and diagonals and seems to work 👍 

But 👆 for multiple lines, the DisplayXsWin ui methods iterate through the amount of lines and print for every line that there was a win 👍 
but you only grant one small win after that 👎 

The easiest solution would be to just multiply the win with the number of matching lines, instead of granting it just once:
```
winnings += SMALL_WIN; // --> grants one small win, regardless of how many lines are hit

winnings += matchingX * SMALL_WIN; // --> grants a small win for each hit line
```


However 👆 keep attention that the amount of matching Rows, Cols and Diagonals is not exclusive!
A player can for example hit multiple rows AND columns but with your current else-if structure if a winning in rows gets detected, cols and diagonals are skipped

**Comment by incredibleLeitman** [comment]
Regarding the issue displaying wins twice, this is just because you call "LogicMethods.GrantWins" twice 😏 
However, this belongs so a separate issue or in the wa chat
