### ISSUE TITLE
simplify code

### ISSUE THREAD

**Issue by incredibleLeitman** [samus9001/Slot-Machine-Game-Exercise#9]
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/d346e2f4e1c2d4e55b9e52388560aa61ed03482e/Program.cs#L191-L213
You have 4 conditions and two variables just to determine if the user wants so play again or exits, this can be simplified

**Comment by incredibleLeitman** [comment]
This is definitely better 👍 but there is still room for more improvement :D

https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/f719308b2edd5a1e288228140ce4c1cbc061e921/Program.cs#L159-L177

- use ConsoleKey instead of KeyChar
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/f719308b2edd5a1e288228140ce4c1cbc061e921/Program.cs#L165-L166
Instead of checking if the retrieved KeyChar (the entered key in it's character representation) converted to upper equals a capital 'Y' you could directly use the pressed key itself by using "Console.ReadKey().Key"

- move second condition within the first
You first check if the balance reaches 0 or lower, within the condition setting the restart value
and afterwards check if the flag was set or if the balance is <= 0 (which should have already triggered the first condition)

So for both cases in the second condition, the first if already was triggered which is an indicator that you can move this codeblock in there

**Comment by samus9001** [comment]
@incredibleLeitman I can't see how I can move the second condition within the first without having nested if statements, which you've advised me not to do previously? Please elaborate in case I'm misunderstanding the suggestion.

**Comment by incredibleLeitman** [comment]
Hm... I don't think there is a problem with nested if statements in general? Maybe I was referring to another block of code or where did I advised this?

For this issue, the origin problem was that you are using much more conditions and variables just to check if the user wants to quit than needed.

**Comment by samus9001** [comment]
> 

just checked the previous feedback and it was referring to a specific block of code where nested if statements were not suitable due to the conditions using the same variable, my mistake thanks for clarifying!

**Comment by incredibleLeitman** [comment]
This is almost perfect 👌 

Just one more thing:
https://github.com/samus9001/Slot-Machine-Game-Exercise/blob/2088c248d8b8b3ce3e798ccd663f01b55a96bf39/Program.cs#L157-L175

You now create a bool variable outside of the condition, but you only use it if balance <= 0
So this means you could move the whole declaration inside your if statement.

But going even further, do you really need an extra variable for that? 😏 
You code also directly use the result of your comparison as condition like
```
if (key == ConsoleKey.Y)
  // restart
else
  return
  ```
